- name: restart docker
  service:
    name: docker
    state: restarted

- name: reload systemd daemon
  systemd:
    daemon_reload: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
